//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppEmployeOperation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_TBL_EMPLOYEE
    {
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public decimal Salary { get; set; }
    }
}
